//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fievus.Windows.Samples.SimpleLoginDemo.Presentation.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fievus.Windows.Samples.SimpleLoginDemo.Presentation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Copyright (C) 2016 Fievus に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loign id or password is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginFailureMessage {
            get {
                return ResourceManager.GetString("LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Login is not available. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LoginNotAvailable {
            get {
                return ResourceManager.GetString("LoginNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Log out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LogoutButtonText {
            get {
                return ResourceManager.GetString("LogoutButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simple Login Demo に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserIdLabel {
            get {
                return ResourceManager.GetString("UserIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hello, {0}! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string UserMessageFormat {
            get {
                return ResourceManager.GetString("UserMessageFormat", resourceCulture);
            }
        }
    }
}
